config/routes.rb
Transparencia::Application.routes.draw do


  resources :monthlies
  resources :travel_expenses
  resources :travel_drivers
  resources :travels
  resources :vehicles
  resources :drivers
  resources :participants
  resources :confirmations
  resources :requests
  resources :addresses
  resources :user_types
  resources :reserve_of_physical_spaces
  resources :reservation_statuses
  resources :alocation_permanents
  resources :spaces
  resources :location_types
  resources :semesters
  resources :recesses
  resources :holidays

  root to: 'users#login'

  # resources :administrators
  get '/administrator/login' => 'administrators#login', as: :administrator_login
  get '/administrator/logout' => 'administrators#logout', as: :administrator_logout
  get '/administrator/welcome' => 'administrators#welcome', as: :administrator_welcome
  post '/administrator/authentication' => 'administrators#authentication', as: :administrator_authentication
  post '/administrator/create' => 'administrators#create', as: :administrator_create
  get '/administrator/new' => 'administrators#new', as: :administrator_new
  
  #páginas de erro
  get '/notfound' => 'portal#notfound', as: :notfound
  
  resources :users do
    resources :durations
  end

  resources :roles
  resources :sectors
  resources :institutions
  resources :functions
  resources :locals
  resources :dailies
  resources :durations
  resources :daily_function_locals

  resources :amounts do
    resources :readjustments
  end

  resources :readjustments
  resources :requests

  get 'alocation_permanents/space/:semester_id/espacos' => 'alocation_permanents#espacos', as: 'alocation_permanents_espacos'
  get 'alocation_permanents/space/:id/:semester_id' => 'alocation_permanents#reserves', as: 'alocation_permanents_space'
  get 'alocation_permanents/space/:id/:semester_id/edit' => 'alocation_permanents#editar', as: 'alocation_permanents_editar'
  post 'alocation_permanents/spaces/:space_id/:semester_id/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'


  get 'reserve_of_physical_spaces/space/all' => 'reserve_of_physical_spaces#espacos', as: 'reserve_of_physical_spaces_espacos'
  get 'reserve_of_physical_spaces/space/:id' => 'reserve_of_physical_spaces#reservas', as: 'reserve_of_physical_spaces_reservas'
  get 'reserve_of_physical_spaces/space/:id/:mes/:ano' => 'reserve_of_physical_spaces#calendario', as: 'calendario'

  get 'reserve/space/:id/new' => 'reserve_of_physical_spaces#new', as: 'reserve_of_physical_spaces_reservas_new'
  
  get '/reserve_of_physical_spaces/aprovacoes/list' => 'reserve_of_physical_spaces#aprovacoes', as: 'aprovacoes'
  get '/reserve_of_physical_spaces/approve/:id' => 'reserve_of_physical_spaces#approve', as: 'approve_reserves'
  get '/reserve_of_physical_spaces/non_approve/:id' => 'reserve_of_physical_spaces#non_approve', as: 'non_approve_reserves'
  post '/reserve_of_physical_spaces/create' => 'reserve_of_physical_spaces#create', as: 'create_reserve'
  post '/reserve_of_physical_spaces/update/:id' => 'reserve_of_physical_spaces#update', as: 'update_reserve'
  #post 'alocation_permanents/spaces/salvar_alocacao' => 'alocation_permanents#salvar_alocacao', as: 'salvar_alocacao'

  #rotas de users
  get '/user/login' => 'users#login', as: 'user_login'
  get '/user/logout' => 'users#logout', as: 'user_logout'
  post '/user/authentication' => 'users#authentication', as: 'user_authentication'
  
  #rotas de confirmations
  get '/confirmations/approve/:id' => 'confirmations#approve', as: 'approve_request'
  post '/confirmations/non_approve/:id' => 'confirmations#non_approve', as: 'non_approve_request'
  get '/confirmations/jus_non_approve/:id' => 'confirmations#non_approve_form', as: 'non_approve_form_request'

  #rota de participants para adicionar users a viagem 
  get '/participants/add/request/:id' => 'participants#index' ,as: 'add_participants'
  post '/participants/add/request/:id' => 'participants#add_participants' ,as: 'add_participants'
   
  #rota para solicitação
  get '/request/user' => 'requests#request_users', as: 'request_users'

  

  #rotas de confirmações
  get '/confirmations/:id/travel' => 'confirmations#travel', as: 'confirmation_travel'
  get '/confirmations/request/:id/travel/new' => 'travels#new', as: 'confirmation_new_travel'
  get '/confirmations/:id/travel/show' => 'confirmations#show_travel', as: 'confirmation_show_travel'

  #rotas para adicionar motoristas a viagem
  get '/travels/:id/travel_drivers' => 'travel_drivers#index', as: 'add_driver'
  post '/travels/:id/travel_drivers' => 'travel_drivers#add_drivers', as: 'add_driver'
  resources :reserve_of_physical_spaces

  get '/relatorios/lista-de-veiculos' => 'reports#imprimir_veiculos', as: 'imprimir_veiculos'
  
end

app/models/monthly.rb
class Monthly < ActiveRecord::Base
  belongs_to :driver

  belongs_to :travel
  attr_accessible :data,
  				  :qtde,
  				  :transfer,
  				  :travel_id,
  				  :driver_id,
  				  :deleted

end

app/controllers/monthlies_controller.rb
class MonthliesController < ApplicationController
  # GET /monthlies
  # GET /monthlies.json
  def index
    @monthlies = Monthly.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @monthlies }
    end
  end

  # GET /monthlies/1
  # GET /monthlies/1.json
  def show
    @monthly = Monthly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @monthly }
    end
  end

  # GET /monthlies/new
  # GET /monthlies/new.json
  def new
    @monthly = Monthly.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @monthly }
    end
  end

  # GET /monthlies/1/edit
  def edit
    @monthly = Monthly.find(params[:id])
  end

  # POST /monthlies
  # POST /monthlies.json
  def create
    @monthly = Monthly.new(params[:monthly])

    respond_to do |format|
      if @monthly.save
        format.html { redirect_to @monthly, notice: 'Monthly was successfully created.' }
        format.json { render json: @monthly, status: :created, location: @monthly }
      else
        format.html { render action: "new" }
        format.json { render json: @monthly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /monthlies/1
  # PUT /monthlies/1.json
  def update
    @monthly = Monthly.find(params[:id])

    respond_to do |format|
      if @monthly.update_attributes(params[:monthly])
        format.html { redirect_to @monthly, notice: 'Monthly was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @monthly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monthlies/1
  # DELETE /monthlies/1.json
  def destroy
    @monthly = Monthly.find(params[:id])
    @monthly.destroy

    respond_to do |format|
      format.html { redirect_to monthlies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/monthlies_helper.rb
module MonthliesHelper
	def numero_diarias(inicio,fim)
        dias = 0
        if(inicio.year == fim.year)
          dias = fim.yday - inicio.yday 
        else
          a = inicio.end_of_year.yday - inicio.yday
          b = fim.yday - fim.at_beginning_of_year.yday 
          dias = a + b
        end
        return(dias + 1)
    end

    def conta_diarias(dias)
       return((dias - 1)+0.5)
    end

    
end

app/views/monthlies/_form.html.erb
<%= form_for(@monthly) do |f| %>
  <% if @monthly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monthly.errors.count, "error") %> prohibited this monthly from being saved:</h2>

      <ul>
      <% @monthly.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month_year %><br />
    <%= f.date_select :month_year %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.date_select :data %>
  </div>
  <div class="field">
    <%= f.label :qtde %><br />
    <%= f.number_field :qtde %>
  </div>
  <div class="field">
    <%= f.label :driver %><br />
    <%= f.text_field :driver %>
  </div>
  <div class="field">
    <%= f.label :travel %><br />
    <%= f.text_field :travel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monthlies/edit.html.erb
<h1>Editing monthly</h1>

<%= render 'form' %>

<%= link_to 'Show', @monthly %> |
<%= link_to 'Back', monthlies_path %>

app/views/monthlies/index.html.erb
<h1>Listando Mensalidade</h1>
<br>
<table class="table table-hover">
  <tr>
    <th>Mes do ano</th>
    <th>Quantidade</th>
    <th>Motorista</th>
    <th>Viagem</th>
    <th>Opções</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @monthlies.each do |monthly| %>
  <tr>
    <td><%= monthly.data %></td>
    <td><%= monthly.qtde %></td>
    <td><%= monthly.driver %></td>
    <td><%= monthly.travel %></td>
    <td>
        <%= link_to monthly, title: 'Visualizar' do  %><i class="icon-user"></i><%end%>
        <%= link_to 'Destroy', monthly, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Monthly', new_monthly_path %>

app/views/monthlies/new.html.erb
<h1>New monthly</h1>

<%= render 'form' %>

<%= link_to 'Back', monthlies_path %>

app/views/monthlies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Month year:</b>
  <%= @monthly.month_year %>
</p>
<p>
  <b>Amount:</b>
  <%= @monthly.amount %>
  <b>Data:</b>
  <%= @monthly.data %>
</p>
<p>
  <b>Qtde:</b>
  <%= @monthly.qtde %>
</p>
<p>
  <b>Daily rate:</b>
  <%= @monthly.daily_rate %>
</p>
<p>
  <b>Driver:</b>
  <%= @monthly.driver %>
</p>
<p>
  <b>Travel:</b>
  <%= @monthly.travel %>
</p>
<%= link_to 'Edit', edit_monthly_path(@monthly) %> |
<%= link_to 'Back', monthlies_path %>